import { useTranslation } from "react-i18next";
import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import SEOHead from "@/components/SEOHead";

const sectionsES = [
  { title: "1. Objeto", content: "Los presentes Términos y Condiciones regulan el acceso y uso de la plataforma Ace-inmotools, un servicio de herramientas digitales basadas en inteligencia artificial destinadas a profesionales del sector inmobiliario en España." },
  { title: "2. Titularidad de la Plataforma", content: "La Plataforma es titularidad de Ace-inmotools." },
  { title: "3. Acceso y registro", content: "Para acceder a las funcionalidades de la Plataforma es necesario completar un proceso de registro proporcionando datos veraces y actualizados." },
  { title: "4. Descripción de los servicios", content: "La Plataforma ofrece herramientas de IA orientadas al sector inmobiliario, incluyendo: generación de descripciones, cálculo de costes, análisis de rentabilidad, consultoría legal, análisis del entorno, guiones, captación, contratos, home staging, informes y roleplay comercial." },
  { title: "5. Planes y período de prueba", content: "La Plataforma puede ofrecer un período de prueba gratuito con acceso limitado. Finalizado dicho período, el usuario deberá suscribirse a un plan de pago." },
  { title: "6. Uso aceptable", content: "El usuario se compromete a utilizar la Plataforma de forma lícita. Queda prohibido:\n\n• Utilizar la Plataforma para fines ilegales.\n• Intentar acceder a áreas restringidas sin autorización.\n• Compartir credenciales con terceros.\n• Utilizar sistemas automatizados (bots, scrapers)." },
  { title: "7. Propiedad intelectual", content: "Todos los derechos de propiedad intelectual de la Plataforma son titularidad de Ace-inmotools o de sus licenciantes." },
  { title: "8. Limitación de responsabilidad", content: "Los contenidos generados por las herramientas de IA tienen carácter orientativo y no constituyen asesoramiento profesional vinculante." },
  { title: "9. Protección de datos", content: "El tratamiento de datos personales se rige por nuestra Política de Privacidad." },
  { title: "10. Disponibilidad del servicio", content: "Ace-inmotools se esforzará por mantener la Plataforma disponible de forma continua." },
  { title: "11. Modificación de los términos", content: "Ace-inmotools se reserva el derecho de modificar estos Términos y Condiciones en cualquier momento." },
  { title: "12. Resolución y suspensión", content: "Ace-inmotools podrá suspender o resolver el acceso del usuario en caso de incumplimiento." },
  { title: "13. Legislación aplicable y jurisdicción", content: "Estos Términos se rigen por la legislación española.\n\n• Reglamento (UE) 2016/679 (RGPD)\n• Ley Orgánica 3/2018 (LOPDGDD)\n• Ley 34/2002 (LSSI-CE)" },
];

const sectionsEN = [
  { title: "1. Purpose", content: "These Terms and Conditions regulate access to and use of the Ace-inmotools platform, a service of AI-based digital tools for real estate professionals in Spain." },
  { title: "2. Platform ownership", content: "The Platform is owned by Ace-inmotools." },
  { title: "3. Access and registration", content: "To access Platform functionalities, users must complete a registration process providing truthful and up-to-date data." },
  { title: "4. Description of services", content: "The Platform offers AI tools for real estate, including: description generation, cost calculation, profitability analysis, legal consulting, area analysis, scripts, lead generation, contracts, home staging, reports and commercial roleplay." },
  { title: "5. Plans and trial period", content: "The Platform may offer a free trial period with limited access. After the trial, users must subscribe to a paid plan." },
  { title: "6. Acceptable use", content: "Users agree to use the Platform lawfully. The following is prohibited:\n\n• Using the Platform for illegal purposes.\n• Attempting to access restricted areas without authorization.\n• Sharing credentials with third parties.\n• Using automated systems (bots, scrapers)." },
  { title: "7. Intellectual property", content: "All intellectual property rights of the Platform belong to Ace-inmotools or its licensors." },
  { title: "8. Limitation of liability", content: "Content generated by AI tools is for guidance only and does not constitute binding professional advice." },
  { title: "9. Data protection", content: "Personal data processing is governed by our Privacy Policy." },
  { title: "10. Service availability", content: "Ace-inmotools will endeavor to keep the Platform continuously available." },
  { title: "11. Modification of terms", content: "Ace-inmotools reserves the right to modify these Terms and Conditions at any time." },
  { title: "12. Termination and suspension", content: "Ace-inmotools may suspend or terminate user access in case of non-compliance." },
  { title: "13. Applicable law and jurisdiction", content: "These Terms are governed by Spanish law.\n\n• Regulation (EU) 2016/679 (GDPR)\n• Organic Law 3/2018 (LOPDGDD)\n• Law 34/2002 (LSSI-CE)" },
];

const TermsOfUsePage = () => {
  const { t, i18n } = useTranslation();
  const isEn = i18n.language?.startsWith("en");
  const sections = isEn ? sectionsEN : sectionsES;

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <div className="mb-8">
          <Button variant="ghost" size="sm" asChild><a href="/auth"><ArrowLeft className="h-4 w-4 mr-1" />{t("legal.back")}</a></Button>
        </div>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <h1 className="text-3xl font-bold mb-2">{t("legal.termsTitle")}</h1>
          <p className="text-sm text-muted-foreground mb-8">{t("legal.lastUpdated")} {new Date().toLocaleDateString(isEn ? "en-US" : "es-ES", { day: "numeric", month: "long", year: "numeric" })}</p>
          <div className="space-y-8">
            {sections.map((s, i) => (
              <motion.section key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.03, duration: 0.4 }}>
                <h2 className="text-lg font-semibold mb-2">{s.title}</h2>
                <p className="text-sm text-muted-foreground whitespace-pre-line leading-relaxed">{s.content}</p>
              </motion.section>
            ))}
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default TermsOfUsePage;
